import type { Card } from "./types";

const c = (id: string, category: Card["category"], text: string, meaning: string, note?: string): Card => ({
  id: `es-${id}`,
  lang: "es",
  text,
  meaning,
  category,
  note,
});

export const ES_DECK: Card[] = [
  // greetings
  c("g1", "greetings", "Hola, buenos días.", "Hello, good morning."),
  c("g2", "greetings", "Buenas tardes.", "Good afternoon.", "Used from lunch until dark."),
  c("g3", "greetings", "Buenas noches.", "Good evening / good night."),
  c("g4", "greetings", "¿Cómo está usted?", "How are you? (formal)", "Use usted with strangers and older people."),
  c("g5", "greetings", "Muchas gracias.", "Thank you very much."),
  c("g6", "greetings", "De nada.", "You're welcome."),
  c("g7", "greetings", "Perdón, ¿habla inglés?", "Sorry, do you speak English?"),
  c("g8", "greetings", "No entiendo. ¿Puede repetir, por favor?", "I don't understand. Can you repeat, please?"),
  c("g9", "greetings", "Más despacio, por favor.", "Slower, please."),
  c("g10", "greetings", "Hasta luego.", "See you later."),
  c("g11", "greetings", "Disculpe.", "Excuse me.", "To get attention or pass by."),
  c("g12", "greetings", "Lo siento.", "I'm sorry."),
  c("g13", "greetings", "Mucho gusto.", "Nice to meet you."),
  c("g14", "greetings", "Con permiso.", "Excuse me (may I pass).", "Common in Latin America when passing someone."),
  // directions
  c("d1", "directions", "¿Dónde está el baño?", "Where is the bathroom?"),
  c("d2", "directions", "¿Dónde está la estación de metro?", "Where is the metro station?"),
  c("d3", "directions", "¿Cómo llego al centro?", "How do I get downtown?"),
  c("d4", "directions", "Siga todo recto.", "Go straight ahead."),
  c("d5", "directions", "Gire a la izquierda.", "Turn left."),
  c("d6", "directions", "Gire a la derecha.", "Turn right."),
  c("d7", "directions", "Está a dos cuadras.", "It's two blocks away.", "In Spain, they say 'manzanas' or 'calles'."),
  c("d8", "directions", "¿Está lejos de aquí?", "Is it far from here?"),
  c("d9", "directions", "¿Se puede ir andando?", "Can you walk there?"),
  c("d10", "directions", "Estoy perdido.", "I'm lost.", "Perdida if you're female."),
  c("d11", "directions", "¿Me lo puede señalar en el mapa?", "Can you show me on the map?"),
  c("d12", "directions", "Al lado de la farmacia.", "Next to the pharmacy."),
  c("d13", "directions", "Enfrente del banco.", "Across from the bank."),
  c("d14", "directions", "En la esquina.", "On the corner."),
  c("d15", "directions", "¿Cuánto se tarda?", "How long does it take?"),
  // food
  c("f1", "food", "Una mesa para dos, por favor.", "A table for two, please."),
  c("f2", "food", "¿Me trae la carta, por favor?", "Can you bring me the menu, please?", "'El menú' often means the fixed-price menu."),
  c("f3", "food", "¿Qué me recomienda?", "What do you recommend?"),
  c("f4", "food", "Quiero esto, por favor.", "I'd like this, please."),
  c("f5", "food", "Para mí, el pollo.", "For me, the chicken."),
  c("f6", "food", "Soy vegetariano.", "I'm vegetarian.", "Vegetariana if you're female."),
  c("f7", "food", "Soy alérgico a los frutos secos.", "I'm allergic to nuts."),
  c("f8", "food", "¿Lleva gluten?", "Does it have gluten?"),
  c("f9", "food", "Sin picante, por favor.", "Not spicy, please."),
  c("f10", "food", "Un vaso de agua, por favor.", "A glass of water, please."),
  c("f11", "food", "Agua con gas / sin gas.", "Sparkling / still water."),
  c("f12", "food", "La cuenta, por favor.", "The bill, please."),
  c("f13", "food", "¿Aceptan tarjeta?", "Do you take cards?"),
  c("f14", "food", "Estaba delicioso.", "It was delicious."),
  c("f15", "food", "¿Está incluida la propina?", "Is the tip included?"),
  c("f16", "food", "Para llevar, por favor.", "To go, please."),
  c("f17", "food", "Un café con leche.", "A coffee with milk."),
  c("f18", "food", "¿Tienen menú del día?", "Do you have a set menu of the day?"),
  // transport
  c("t1", "transport", "¿Cuánto cuesta ir al aeropuerto?", "How much is it to the airport?"),
  c("t2", "transport", "Lléveme a esta dirección, por favor.", "Take me to this address, please."),
  c("t3", "transport", "Un billete de ida y vuelta.", "A round-trip ticket.", "In Latin America: 'boleto'."),
  c("t4", "transport", "¿A qué hora sale el próximo tren?", "What time does the next train leave?"),
  c("t5", "transport", "¿De qué andén sale?", "Which platform does it leave from?"),
  c("t6", "transport", "¿Este autobús va al centro?", "Does this bus go downtown?"),
  c("t7", "transport", "Pare aquí, por favor.", "Stop here, please."),
  c("t8", "transport", "¿Puede poner el taxímetro?", "Can you turn on the meter?"),
  c("t9", "transport", "¿Dónde puedo comprar billetes?", "Where can I buy tickets?"),
  c("t10", "transport", "Quiero alquilar un coche.", "I want to rent a car.", "'Carro' in most of Latin America."),
  c("t11", "transport", "¿Hay retraso?", "Is there a delay?"),
  // hotel
  c("h1", "hotel", "Tengo una reserva a nombre de...", "I have a reservation under the name..."),
  c("h2", "hotel", "¿Tienen habitaciones libres?", "Do you have rooms available?"),
  c("h3", "hotel", "¿A qué hora es el desayuno?", "What time is breakfast?"),
  c("h4", "hotel", "¿Cuál es la contraseña del wifi?", "What's the wifi password?"),
  c("h5", "hotel", "El aire acondicionado no funciona.", "The air conditioning doesn't work."),
  c("h6", "hotel", "¿Me puede guardar la maleta?", "Can you keep my suitcase?"),
  c("h7", "hotel", "Quiero hacer el check-out.", "I'd like to check out."),
  c("h8", "hotel", "¿Hay una caja fuerte?", "Is there a safe?"),
  c("h9", "hotel", "Necesito toallas limpias.", "I need clean towels."),
  // shopping
  c("s1", "shopping", "¿Cuánto cuesta?", "How much does it cost?"),
  c("s2", "shopping", "Es muy caro.", "It's very expensive."),
  c("s3", "shopping", "¿Me hace un descuento?", "Can you give me a discount?"),
  c("s4", "shopping", "Solo estoy mirando.", "I'm just looking."),
  c("s5", "shopping", "¿Tiene una talla más grande?", "Do you have a bigger size?"),
  c("s6", "shopping", "Me lo llevo.", "I'll take it."),
  c("s7", "shopping", "¿Dónde hay un cajero automático?", "Where is there an ATM?"),
  c("s8", "shopping", "¿Puedo pagar en efectivo?", "Can I pay in cash?"),
  c("s9", "shopping", "¿Me da el recibo?", "Can I have the receipt?"),
  c("s10", "shopping", "¿A qué hora cierran?", "What time do you close?"),
  // emergencies
  c("e1", "emergencies", "¡Ayuda!", "Help!"),
  c("e2", "emergencies", "Necesito un médico.", "I need a doctor."),
  c("e3", "emergencies", "Llame a la policía.", "Call the police."),
  c("e4", "emergencies", "Me han robado.", "I've been robbed."),
  c("e5", "emergencies", "He perdido mi pasaporte.", "I've lost my passport."),
  c("e6", "emergencies", "¿Dónde está la farmacia más cercana?", "Where is the nearest pharmacy?"),
  c("e7", "emergencies", "Me duele aquí.", "It hurts here."),
  c("e8", "emergencies", "Es una emergencia.", "It's an emergency."),
  c("e9", "emergencies", "¿Dónde está el hospital?", "Where is the hospital?"),
  // numbers and time
  c("n1", "numbers", "uno, dos, tres, cuatro, cinco", "one, two, three, four, five"),
  c("n2", "numbers", "seis, siete, ocho, nueve, diez", "six, seven, eight, nine, ten"),
  c("n3", "numbers", "veinte, treinta, cincuenta, cien", "twenty, thirty, fifty, one hundred"),
  c("n4", "numbers", "¿Qué hora es?", "What time is it?"),
  c("n5", "numbers", "Son las tres y media.", "It's three thirty."),
  c("n6", "numbers", "A las ocho de la mañana.", "At eight in the morning."),
  c("n7", "numbers", "Hoy, mañana, ayer.", "Today, tomorrow, yesterday."),
  c("n8", "numbers", "El lunes, el martes, el miércoles.", "Monday, Tuesday, Wednesday."),
  c("n9", "numbers", "El jueves, el viernes, el fin de semana.", "Thursday, Friday, the weekend."),
  c("n10", "numbers", "Quince minutos.", "Fifteen minutes."),
  // small talk
  c("m1", "smalltalk", "Me llamo... ¿Y usted?", "My name is... And you?"),
  c("m2", "smalltalk", "Soy de Estados Unidos.", "I'm from the United States."),
  c("m3", "smalltalk", "Estoy aquí de vacaciones.", "I'm here on vacation."),
  c("m4", "smalltalk", "Estoy aprendiendo español.", "I'm learning Spanish."),
  c("m5", "smalltalk", "¿Qué me recomienda ver en la ciudad?", "What do you recommend seeing in the city?"),
  c("m6", "smalltalk", "Me encanta la comida de aquí.", "I love the food here."),
  c("m7", "smalltalk", "¿A qué se dedica?", "What do you do for work?"),
  c("m8", "smalltalk", "Trabajo en tecnología.", "I work in tech."),
  c("m9", "smalltalk", "Hace buen tiempo hoy.", "The weather is nice today."),
  c("m10", "smalltalk", "¿Cuánto tiempo lleva viviendo aquí?", "How long have you lived here?"),
  // news
  c("w1", "news", "las noticias", "the news"),
  c("w2", "news", "el gobierno", "the government"),
  c("w3", "news", "las elecciones", "the elections"),
  c("w4", "news", "la economía", "the economy"),
  c("w5", "news", "el cambio climático", "climate change"),
  c("w6", "news", "¿Qué opina de...?", "What do you think about...?"),
  c("w7", "news", "Creo que...", "I think that..."),
  c("w8", "news", "Según el periódico...", "According to the newspaper..."),
  c("w9", "news", "Estoy de acuerdo.", "I agree."),
  c("w10", "news", "No estoy de acuerdo.", "I disagree."),
  c("w11", "news", "el titular", "the headline"),
  c("w12", "news", "la huelga", "the strike"),
  c("w13", "news", "el partido", "the match / the (political) party", "Context tells you which."),
];
