import type { Card } from "./types";

const c = (id: string, category: Card["category"], text: string, reading: string, meaning: string, note?: string): Card => ({
  id: `zh-${id}`,
  lang: "zh",
  text,
  reading,
  meaning,
  category,
  note,
});

export const ZH_DECK: Card[] = [
  // greetings
  c("g1", "greetings", "你好。", "nǐ hǎo", "Hello."),
  c("g2", "greetings", "早上好。", "zǎoshang hǎo", "Good morning."),
  c("g3", "greetings", "谢谢。", "xièxie", "Thank you."),
  c("g4", "greetings", "不客气。", "bú kèqi", "You're welcome."),
  c("g5", "greetings", "对不起。", "duìbuqǐ", "Sorry."),
  c("g6", "greetings", "没关系。", "méi guānxi", "It's fine / no problem."),
  c("g7", "greetings", "请问，你会说英语吗？", "qǐngwèn, nǐ huì shuō Yīngyǔ ma?", "Excuse me, do you speak English?"),
  c("g8", "greetings", "我听不懂。", "wǒ tīng bu dǒng", "I don't understand (what I hear)."),
  c("g9", "greetings", "请再说一遍。", "qǐng zài shuō yí biàn", "Please say it again."),
  c("g10", "greetings", "请说慢一点。", "qǐng shuō màn yìdiǎn", "Please speak more slowly."),
  c("g11", "greetings", "再见。", "zàijiàn", "Goodbye."),
  c("g12", "greetings", "不好意思。", "bù hǎoyìsi", "Excuse me / sorry to bother.", "The everyday way to get attention."),
  c("g13", "greetings", "我叫...", "wǒ jiào...", "My name is..."),
  c("g14", "greetings", "很高兴认识你。", "hěn gāoxìng rènshi nǐ", "Nice to meet you."),
  // directions
  c("d1", "directions", "洗手间在哪里？", "xǐshǒujiān zài nǎlǐ?", "Where is the bathroom?"),
  c("d2", "directions", "地铁站在哪里？", "dìtiě zhàn zài nǎlǐ?", "Where is the metro station?"),
  c("d3", "directions", "怎么去市中心？", "zěnme qù shì zhōngxīn?", "How do I get to the city center?"),
  c("d4", "directions", "一直走。", "yìzhí zǒu", "Go straight."),
  c("d5", "directions", "左转。", "zuǒ zhuǎn", "Turn left."),
  c("d6", "directions", "右转。", "yòu zhuǎn", "Turn right."),
  c("d7", "directions", "离这里远吗？", "lí zhèlǐ yuǎn ma?", "Is it far from here?"),
  c("d8", "directions", "可以走路去吗？", "kěyǐ zǒulù qù ma?", "Can I walk there?"),
  c("d9", "directions", "我迷路了。", "wǒ mílù le", "I'm lost."),
  c("d10", "directions", "在银行对面。", "zài yínháng duìmiàn", "Across from the bank."),
  c("d11", "directions", "在药店旁边。", "zài yàodiàn pángbiān", "Next to the pharmacy."),
  c("d12", "directions", "在路口。", "zài lùkǒu", "At the intersection."),
  c("d13", "directions", "要多长时间？", "yào duō cháng shíjiān?", "How long does it take?"),
  c("d14", "directions", "请在地图上指给我看。", "qǐng zài dìtú shàng zhǐ gěi wǒ kàn", "Please point it out on the map."),
  // food
  c("f1", "food", "两位。", "liǎng wèi", "Table for two.", "位 is the polite measure word for people."),
  c("f2", "food", "请给我菜单。", "qǐng gěi wǒ càidān", "Please give me the menu."),
  c("f3", "food", "你推荐什么？", "nǐ tuījiàn shénme?", "What do you recommend?"),
  c("f4", "food", "我要这个。", "wǒ yào zhège", "I want this one.", "Pointing at the menu is completely normal."),
  c("f5", "food", "我不吃肉。", "wǒ bù chī ròu", "I don't eat meat."),
  c("f6", "food", "我对花生过敏。", "wǒ duì huāshēng guòmǐn", "I'm allergic to peanuts."),
  c("f7", "food", "不要辣。", "bú yào là", "No spice."),
  c("f8", "food", "微辣。", "wēi là", "Mildly spicy."),
  c("f9", "food", "请给我一杯水。", "qǐng gěi wǒ yì bēi shuǐ", "Please give me a glass of water."),
  c("f10", "food", "买单。", "mǎidān", "The bill, please."),
  c("f11", "food", "可以用微信支付吗？", "kěyǐ yòng Wēixìn zhīfù ma?", "Can I pay with WeChat Pay?"),
  c("f12", "food", "很好吃！", "hěn hǎochī!", "Delicious!"),
  c("f13", "food", "打包。", "dǎbāo", "To go / pack it up."),
  c("f14", "food", "一杯咖啡。", "yì bēi kāfēi", "One coffee."),
  c("f15", "food", "有没有英文菜单？", "yǒu méiyǒu Yīngwén càidān?", "Is there an English menu?"),
  c("f16", "food", "服务员！", "fúwùyuán!", "Waiter!", "Normal and not rude."),
  c("f17", "food", "这个是什么？", "zhège shì shénme?", "What is this?"),
  c("f18", "food", "不要香菜。", "bú yào xiāngcài", "No cilantro."),
  // transport
  c("t1", "transport", "去机场多少钱？", "qù jīchǎng duōshao qián?", "How much to the airport?"),
  c("t2", "transport", "请送我去这个地址。", "qǐng sòng wǒ qù zhège dìzhǐ", "Please take me to this address."),
  c("t3", "transport", "一张去北京的票。", "yì zhāng qù Běijīng de piào", "One ticket to Beijing."),
  c("t4", "transport", "下一班车几点？", "xià yì bān chē jǐ diǎn?", "What time is the next train / bus?"),
  c("t5", "transport", "在哪个站台？", "zài nǎge zhàntái?", "Which platform?"),
  c("t6", "transport", "这辆车去市中心吗？", "zhè liàng chē qù shì zhōngxīn ma?", "Does this bus go downtown?"),
  c("t7", "transport", "请在这里停。", "qǐng zài zhèlǐ tíng", "Please stop here."),
  c("t8", "transport", "请打表。", "qǐng dǎ biǎo", "Please use the meter."),
  c("t9", "transport", "在哪里买票？", "zài nǎlǐ mǎi piào?", "Where do I buy tickets?"),
  c("t10", "transport", "我要叫滴滴。", "wǒ yào jiào Dīdī", "I'll call a Didi (ride-hail)."),
  c("t11", "transport", "高铁", "gāotiě", "high-speed rail"),
  // hotel
  c("h1", "hotel", "我有预订。", "wǒ yǒu yùdìng", "I have a reservation."),
  c("h2", "hotel", "有空房间吗？", "yǒu kōng fángjiān ma?", "Do you have rooms available?"),
  c("h3", "hotel", "早餐几点？", "zǎocān jǐ diǎn?", "What time is breakfast?"),
  c("h4", "hotel", "WiFi 密码是什么？", "WiFi mìmǎ shì shénme?", "What's the wifi password?"),
  c("h5", "hotel", "空调坏了。", "kōngtiáo huài le", "The air conditioning is broken."),
  c("h6", "hotel", "可以帮我保管行李吗？", "kěyǐ bāng wǒ bǎoguǎn xíngli ma?", "Can you store my luggage?"),
  c("h7", "hotel", "我要退房。", "wǒ yào tuìfáng", "I'd like to check out."),
  c("h8", "hotel", "请给我护照。", "qǐng gěi wǒ hùzhào", "Please give me my passport back.", "Hotels register your passport at check-in."),
  c("h9", "hotel", "我需要干净的毛巾。", "wǒ xūyào gānjìng de máojīn", "I need clean towels."),
  // shopping
  c("s1", "shopping", "多少钱？", "duōshao qián?", "How much?"),
  c("s2", "shopping", "太贵了。", "tài guì le", "Too expensive."),
  c("s3", "shopping", "便宜一点吧。", "piányi yìdiǎn ba", "A bit cheaper, please.", "Bargaining is normal in markets, not in stores."),
  c("s4", "shopping", "我随便看看。", "wǒ suíbiàn kànkan", "I'm just looking."),
  c("s5", "shopping", "有大一点的吗？", "yǒu dà yìdiǎn de ma?", "Do you have a bigger one?"),
  c("s6", "shopping", "我要了。", "wǒ yào le", "I'll take it."),
  c("s7", "shopping", "取款机在哪里？", "qǔkuǎnjī zài nǎlǐ?", "Where is the ATM?"),
  c("s8", "shopping", "可以用现金吗？", "kěyǐ yòng xiànjīn ma?", "Can I use cash?"),
  c("s9", "shopping", "请给我发票。", "qǐng gěi wǒ fāpiào", "Please give me a receipt."),
  c("s10", "shopping", "几点关门？", "jǐ diǎn guānmén?", "What time do you close?"),
  c("s11", "shopping", "扫码", "sǎo mǎ", "scan the QR code"),
  // emergencies
  c("e1", "emergencies", "救命！", "jiùmìng!", "Help!"),
  c("e2", "emergencies", "我需要看医生。", "wǒ xūyào kàn yīshēng", "I need to see a doctor."),
  c("e3", "emergencies", "请叫警察。", "qǐng jiào jǐngchá", "Please call the police."),
  c("e4", "emergencies", "我的东西被偷了。", "wǒ de dōngxi bèi tōu le", "My things were stolen."),
  c("e5", "emergencies", "我的护照丢了。", "wǒ de hùzhào diū le", "I lost my passport."),
  c("e6", "emergencies", "最近的药店在哪里？", "zuì jìn de yàodiàn zài nǎlǐ?", "Where is the nearest pharmacy?"),
  c("e7", "emergencies", "这里疼。", "zhèlǐ téng", "It hurts here."),
  c("e8", "emergencies", "医院在哪里？", "yīyuàn zài nǎlǐ?", "Where is the hospital?"),
  c("e9", "emergencies", "我不舒服。", "wǒ bù shūfu", "I feel unwell."),
  // numbers and time
  c("n1", "numbers", "一、二、三、四、五", "yī, èr, sān, sì, wǔ", "one, two, three, four, five"),
  c("n2", "numbers", "六、七、八、九、十", "liù, qī, bā, jiǔ, shí", "six, seven, eight, nine, ten"),
  c("n3", "numbers", "二十、五十、一百、一千", "èrshí, wǔshí, yìbǎi, yìqiān", "twenty, fifty, one hundred, one thousand"),
  c("n4", "numbers", "现在几点？", "xiànzài jǐ diǎn?", "What time is it now?"),
  c("n5", "numbers", "三点半。", "sān diǎn bàn", "Three thirty."),
  c("n6", "numbers", "早上八点。", "zǎoshang bā diǎn", "Eight in the morning."),
  c("n7", "numbers", "今天、明天、昨天", "jīntiān, míngtiān, zuótiān", "today, tomorrow, yesterday"),
  c("n8", "numbers", "星期一、星期二、星期三", "xīngqīyī, xīngqī'èr, xīngqīsān", "Monday, Tuesday, Wednesday"),
  c("n9", "numbers", "周末", "zhōumò", "the weekend"),
  c("n10", "numbers", "十五分钟", "shíwǔ fēnzhōng", "fifteen minutes"),
  c("n11", "numbers", "两个", "liǎng ge", "two (of something)", "Use 两 not 二 before measure words."),
  // small talk
  c("m1", "smalltalk", "你叫什么名字？", "nǐ jiào shénme míngzi?", "What's your name?"),
  c("m2", "smalltalk", "我是美国人。", "wǒ shì Měiguó rén", "I'm American."),
  c("m3", "smalltalk", "我来这里旅游。", "wǒ lái zhèlǐ lǚyóu", "I'm here traveling."),
  c("m4", "smalltalk", "我在学中文。", "wǒ zài xué Zhōngwén", "I'm learning Chinese."),
  c("m5", "smalltalk", "你推荐去哪里玩？", "nǐ tuījiàn qù nǎlǐ wán?", "Where do you recommend visiting?"),
  c("m6", "smalltalk", "我很喜欢这里的菜。", "wǒ hěn xǐhuan zhèlǐ de cài", "I really like the food here."),
  c("m7", "smalltalk", "你做什么工作？", "nǐ zuò shénme gōngzuò?", "What do you do for work?"),
  c("m8", "smalltalk", "我做软件。", "wǒ zuò ruǎnjiàn", "I work in software."),
  c("m9", "smalltalk", "今天天气很好。", "jīntiān tiānqì hěn hǎo", "The weather is nice today."),
  c("m10", "smalltalk", "你是哪里人？", "nǐ shì nǎlǐ rén?", "Where are you from?"),
  c("m11", "smalltalk", "吃了吗？", "chī le ma?", "Have you eaten?", "A classic friendly greeting, not an invitation."),
  // news
  c("w1", "news", "新闻", "xīnwén", "the news"),
  c("w2", "news", "政府", "zhèngfǔ", "government"),
  c("w3", "news", "经济", "jīngjì", "the economy"),
  c("w4", "news", "气候变化", "qìhòu biànhuà", "climate change"),
  c("w5", "news", "你觉得...怎么样？", "nǐ juéde... zěnmeyàng?", "What do you think about...?"),
  c("w6", "news", "我觉得...", "wǒ juéde...", "I think..."),
  c("w7", "news", "我同意。", "wǒ tóngyì", "I agree."),
  c("w8", "news", "我不同意。", "wǒ bù tóngyì", "I disagree."),
  c("w9", "news", "标题", "biāotí", "headline"),
  c("w10", "news", "科技", "kējì", "technology"),
  c("w11", "news", "人工智能", "réngōng zhìnéng", "artificial intelligence"),
  c("w12", "news", "据报道...", "jù bàodào...", "According to reports..."),
  c("w13", "news", "问题", "wèntí", "problem / question"),
];
